# Generated by Django 5.0.6 on 2024-06-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared',
            name='shared_content',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shared',
            name='shared_title',
            field=models.CharField(max_length=100),
        ),
    ]
