# Generated by Django 5.0.6 on 2024-06-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='user',
        ),
    ]
