# Generated by Django 5.0.6 on 2024-06-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_directory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='directory',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=models.CharField(max_length=200),
        ),
    ]
