# Generated by Django 5.0.6 on 2024-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_directory_library_alter_directory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='question_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
