# Generated by Django 5.0.6 on 2024-06-04 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_directory_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='library',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='main.library'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shared',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory', to='main.directory'),
        ),
    ]
