# Generated by Django 5.0.6 on 2024-06-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_directory_library_alter_directory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='concept',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
