# Generated by Django 4.1 on 2024-03-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sharedtag_shared_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='shared',
        ),
        migrations.AddField(
            model_name='shared',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.directory'),
        ),
    ]
