# Generated by Django 4.1 on 2024-05-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_library_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_explaination',
            new_name='question_explanation',
        ),
    ]
