# Generated by Django 4.1 on 2024-05-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_question_last_solveed_question_last_solved'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='choice',
        ),
    ]
