# Generated by Django 4.1 on 2024-05-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_directory_user_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(blank=True, max_length=8000),
        ),
    ]
