# Generated by Django 4.1 on 2024-03-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shared',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SharedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='main.shared')),
            ],
            options={
                'db_table': 'shared_tag',
            },
        ),
    ]
