# Generated by Django 4.1 on 2024-03-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_successed', models.IntegerField(null=True)),
                ('concept', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=30)),
                ('question_type', models.CharField(max_length=100, null=True)),
                ('directory_last_access', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'directory',
            },
        ),
        migrations.AlterUniqueTogether(
            name='library',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique library title'),
        ),
        migrations.AddField(
            model_name='directory',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.library'),
        ),
        migrations.AddField(
            model_name='directory',
            name='shared',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory', to='main.shared'),
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('library', 'title'), name='unique directory title'),
        ),
    ]
