# Generated by Django 4.1 on 2024-03-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_directory_alter_library_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('question_title', models.CharField(max_length=1000)),
                ('question_content', models.CharField(max_length=2000, null=True)),
                ('question_answer', models.CharField(max_length=100)),
                ('question_explaination', models.CharField(max_length=2000)),
                ('question_type', models.IntegerField()),
                ('is_scrapped', models.BooleanField(default=False)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='main.directory')),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
