# Generated by Django 4.1 on 2024-03-31 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtag',
            name='shared',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_tag', to='main.shared'),
        ),
        migrations.AddConstraint(
            model_name='sharedtag',
            constraint=models.UniqueConstraint(fields=('shared', 'name'), name='unique shared tag name'),
        ),
    ]
