# Generated by Django 4.1 on 2024-04-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_directory_shared_shared_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
