# Generated by Django 4.1 on 2024-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_custom_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='directory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directory',
            name='is_scrap_directory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='library',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
