# Generated by Django 4.1 on 2024-05-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='is_deleted',
        ),
    ]
