# Generated by Django 4.1 on 2024-05-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_question_explaination_question_question_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='last_solveed',
        ),
        migrations.AddField(
            model_name='question',
            name='last_solved',
            field=models.BooleanField(null=True),
        ),
    ]
