# Generated by Django 4.1 on 2024-05-15 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type_data',
            field=models.CharField(default='Image', max_length=10),
            preserve_default=False,
        ),
    ]
